export const GET_RECIPES_USER = "GET_RECIPES_USER"
export const GET_RECIPES_DIET = "GET_RECIPES_DIET"
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME"
export const GET_RECIPES_SPOONACULAR = "GET_RECIPES_SPOONACULAR"
export const GET_RECIPES_BY_NAME_API = "GET_RECIPES_BY_NAME_API"
export const GET_RECIPES_DIET_API = "GET_RECIPES_DIET_API"
export const GET_RECIPES_HEALTH = "GET_RECIPES_HEALTH"
export const DELETE_RECIPE = "DELETE_RECIPE"



export const NEXT_PAGE = "NEXT_PAGE"
export const PREV_PAGE = "PREV_PAGE"
export const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY"
export const CHANGE_PAGE = "CHANGE_PAGE"